In [8]:
# auto reload modules
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
import numpy as np
import json

In [10]:
#import PES_models as pmodel, PES_models_bonding_features as bond_pmodel
from PES_models_bonding_features import *
from PES_data_processor import *

### save Hn as numpy array

In [17]:
f = open("data/h4/H4_Hinde_QZ.txt")
data = json.load(f)
H4 = np.array(data['data'])
np.savetxt("data/h4/h4_QZ_data.txt", H4)

f = open("data/h4/H4_Hinde_TZ.txt")
data = json.load(f)
H4 = np.array(data['data'])
np.savetxt("data/h4/h4_TZ_data.txt", H4)

TZ


In [2]:
f = open("data/h5/H5_Tablero.txt")
data = json.load(f)
H5 = np.array(data['data'])
np.savetxt("data/h5/H5_data.txt", H5)

In [5]:
# add .txt format for H3
H = np.load("data/h3/h3_data.npy")
np.savetxt("data/h3/h3_data.txt", H)

### check X

In [50]:
Hn = np.loadtxt("data/h4/h4_TZ_data.txt")
R = Hn[:, :-1]
idx = 100
print(R[idx])
V = Hn[:, -1]
X = np.load("data/h4/h4_TZ_coord.npy")
print(X.shape)
print(X[idx])
print(np.linalg.norm(X[idx][2] - X[idx][3]))

[1.1        4.50249931 4.67038542 4.67038542 4.50249931 1.4       ]
(855, 4, 3)
[[-2.96666523e-08  5.50000000e-01 -2.25000000e+00]
 [ 1.74017625e-08 -5.50000000e-01 -2.25000000e+00]
 [ 1.23587181e-08  7.00000000e-01  2.25000000e+00]
 [-2.46236079e-08 -7.00000000e-01  2.25000000e+00]]
1.4


In [66]:
H = np.loadtxt("data/h5/h5_data.txt")
n_atom = 5
R = H[:, :-1]; V = H[:, -1]
X = np.zeros((H.shape[0], n_atom, 3))
for i, x in enumerate(X):
    X[i] = distance_to_coord_v2(R[i], n_atom)[:, 2:]
    print(X[i])

'''
print(R[0])
x = distance_to_coord_v2(R[0], n_atom)
#x = x[:, 2:]
print(x)
for i in range(n_atom):
    for j in range(n_atom):
        if j > i:
            print(np.linalg.norm(x[i]-x[j]))
'''
# distance from X:
R_x = np.zeros(R.shape)
threshold = 1e-3
for i in range(X.shape[0]):
    c = 0
    for j in range(X.shape[1]):
        for k in range(X.shape[1]):
            if k > j:
                R_x[i][c] = np.linalg.norm(X[i][j]-X[i][k])
                c += 1
T = np.abs(R - R_x) < threshold
x, y = np.where(T == False)
print(len(R), len(R[x]))
print(R[-200])
print(R_x[-200])

[[ 2.58971285e-03 -1.70256757e-04 -3.44081904e-22]
 [-6.47625050e-04 -6.99964953e-01  5.95905088e+00]
 [-6.47625050e-04 -6.99964953e-01 -5.95905088e+00]
 [-6.47231379e-04  7.00050082e-01 -5.95900088e+00]
 [-6.47231379e-04  7.00050082e-01  5.95900088e+00]]
[[ 0.00000000e+00  2.71715621e-08  0.00000000e+00]
 [ 0.00000000e+00 -6.38996501e-09  5.00000000e+00]
 [ 0.00000000e+00 -2.67004505e-10  6.40000000e+00]
 [ 0.00000000e+00 -6.10206721e-09 -5.00000000e+00]
 [ 0.00000000e+00 -4.91924660e-10 -6.40000000e+00]]
[[ 3.55255975e-09 -2.01326253e-08  6.40120000e+00]
 [ 9.42658342e-09  7.59699034e-08  5.00000000e+00]
 [-4.83718060e-08 -5.47768728e-09  0.00000000e+00]
 [ 1.46965408e-08 -5.86296455e-08 -5.00000000e+00]
 [-5.63822614e-10  8.50035592e-08 -6.40120000e+00]]
[[ 7.33190289e-03  2.53739431e-15 -2.55044016e-16]
 [-1.83297572e-03 -7.00059994e-01  6.96490603e+00]
 [-1.83297572e-03 -7.00059994e-01 -6.96490603e+00]
 [-1.83297572e-03  7.00059994e-01 -6.96490603e+00]
 [-1.83297572e-03  7.0005999

 [-0.30464168  1.13304306  1.66359813]]
[[ 0.82377405  1.41901184 -1.23250419]
 [-0.99024077  0.03054132 -1.68814025]
 [ 0.39931306 -1.85672805 -0.73220183]
 [ 0.07179534 -0.72586817  1.98924815]
 [-0.30464168  1.13304306  1.66359813]]
[[ 0.11051864  0.3584243  -2.27681027]
 [-0.61507288  1.96520689  0.14540688]
 [ 1.12136902  0.38278402  1.67301562]
 [-0.66821052 -1.22148599  2.16585282]
 [ 0.05139574 -1.48492922 -1.70746505]]
[[ 7.19792638e-09 -4.58150601e-03  1.47027975e-01]
 [ 1.07348335e-08  2.21535324e-03 -1.60778213e+00]
 [ 4.44112228e-09  1.35365225e-03 -2.84828204e+00]
 [ 6.41782339e-09  5.26051632e-03  2.77601756e+00]
 [ 7.19792638e-09 -4.24801581e-03  1.53301863e+00]]
[[ 0.47952673  0.77897049 -1.54859398]
 [ 0.32745278  1.68113952  0.540126  ]
 [-0.83855798  0.78208999  1.40066502]
 [ 0.37944375 -1.91947568  2.20516101]
 [-0.34786529 -1.32272433 -2.59735806]]
[[ 0.00000000e+00  1.02401442e+00 -2.48030351e+00]
 [-7.60219077e-17  7.61810888e-01  2.37081668e+00]
 [-3.24284745e

 [-7.15488682e-01 -1.51272129e-01  4.27805000e+00]]
[[ 0.42688349  2.15401913 -0.6772002 ]
 [-0.48294641 -0.09039853 -2.20452245]
 [ 0.60825671 -1.70463376  0.06198225]
 [-0.26072719 -1.0068701   0.27906817]
 [-0.29146659  0.64788327  2.54067224]]
[[ 0.00000000e+00  4.40519565e+00 -5.28992664e-01]
 [-4.28476869e-16 -9.32495541e-01 -4.53590346e+00]
 [ 5.50551620e-17 -1.66275551e+00 -3.54217027e+00]
 [-2.34835000e+00 -9.04972302e-01  4.30353320e+00]
 [ 2.34835000e+00 -9.04972302e-01  4.30353320e+00]]
[[ 0.08756935  2.02908612 -0.66975392]
 [ 0.08583187  0.04195964 -0.36003158]
 [ 0.11809905 -1.24588774 -2.21535299]
 [-1.30795186 -0.3461465   1.26799974]
 [ 1.01645159 -0.47901153  1.97713874]]
[[ 0.2007793   1.09148218 -0.75207124]
 [-0.55329757  1.07482288 -2.28002529]
 [ 1.6529424  -0.18695669  0.70742392]
 [-0.85163215  0.50575193  3.06962607]
 [-0.44879199 -2.4851003  -0.74495346]]
[[ 2.46957515e-15 -1.54925497e-21  7.05713895e-23]
 [-7.99218368e-03 -1.24997445e+00  3.49999087e+00]
 [

 [-0.02357094  1.53400626  4.00465805]]
[[ 0.68782252  0.65319098 -0.72646417]
 [ 0.03498178 -0.88743541 -0.41821078]
 [ 0.08392216 -0.47660634  2.27084349]
 [-0.34200032 -0.39019197 -1.62660034]
 [-0.46472615  1.10104273  0.5004318 ]]
[[ 0.79700768  1.42615421 -0.52538759]
 [-0.61001261  1.01726749  1.39568949]
 [ 0.07458453 -0.53329108 -1.99853679]
 [ 0.79846316 -1.34578788  1.40713207]
 [-1.06004276 -0.56434274 -0.27889718]]
[[ 0.13722277  0.3109999  -1.02556503]
 [ 0.04782619  0.81119502 -0.13609922]
 [-0.09833839 -1.1550956  -2.17842656]
 [ 0.01595739 -1.61588594  2.32612435]
 [-0.10266796  1.64878663  1.01396645]]
[[ 0.00000000e+00 -1.22094512e-08  2.09800000e-02]
 [ 0.00000000e+00 -3.26857001e-08  2.89108000e+00]
 [ 0.00000000e+00 -3.40044476e-08 -2.97732000e+00]
 [ 0.00000000e+00 -1.07942476e-08  1.13918000e+00]
 [ 0.00000000e+00 -5.40784908e-09 -1.07392000e+00]]
[[ 0.30727112 -0.68192046  0.02254264]
 [-0.52579583 -0.90410935  2.16732858]
 [ 0.05754192 -3.12776979 -2.5475738 ]

 [-1.07863598e-16 -8.23666057e-19  1.00000500e+01]]
[[ 0.60598346  0.26030066 -0.43182469]
 [-0.22012884  0.76768262  0.35247269]
 [-0.05349342 -1.17436403 -0.48581427]
 [-0.0813098  -0.0873119   2.68152241]
 [-0.25105141  0.23369266 -2.11635615]]
[[ 1.21024395e+00 -7.28668312e-02  0.00000000e+00]
 [-6.68226503e-01 -1.01166859e+00  4.32972624e-16]
 [-5.42017449e-01  1.08453542e+00 -4.33003460e-16]
 [-5.26707851e-17 -9.47281730e-16 -3.90000000e+00]
 [-5.26707851e-17 -9.47281730e-16  3.90000000e+00]]
[[ 1.18795616e+00  1.61443093e-16 -3.33335107e-05]
 [-2.97000825e-01 -1.04999536e+00 -1.04998703e+00]
 [-2.97000825e-01  1.04999536e+00 -1.04998703e+00]
 [-2.96977254e-01  1.04994536e+00  1.05000369e+00]
 [-2.96977254e-01 -1.04994536e+00  1.05000369e+00]]
[[ 1.27563282e-01  1.14763276e+00  0.00000000e+00]
 [-1.05766076e+00 -4.63343335e-01 -2.44240967e-16]
 [ 9.30097480e-01 -6.84289421e-01  2.44257373e-16]
 [-3.13774123e-17  1.02562955e-17 -2.20000000e+00]
 [-3.45395904e-16  2.98824512e-17  2

2799 0
[ 9.1027  3.6577 10.9634 10.9634  5.7866  7.5319  7.5319  9.5097  9.5097
 11.0382]
[ 9.1027      3.65770138 10.9634001  10.9634001   5.78660081  7.53190013
  7.53190013  9.50970015  9.50970015 11.0382    ]


### split data directly for every functional other than our PES 

In [57]:
Hn = np.load("data/h3/h3_data.npy")
cv_idx = np.load("data/h3/crossval_indices_1.npy",allow_pickle=True)
train = Hn[cv_idx[0]]; test = Hn[cv_idx[1]]
R_train = train[:, :-1]
V_train = train[:, -1]
R_test = test[:, :-1]
V_test = test[:, -1]

In [61]:
# save to file:
# ab initio (training) data:
with open('data/h3/abinitio_data.txt', "w") as f:
    for i in range(R_train.shape[0]):
        string = ""
        for j in range(R_train.shape[1]):
            string += str(R_train[i][j])+"\t"
        f.write(string+str(V_train[i])+"\t"+str(1.000)+"\n")

with open('data/h3/test_data.txt', "w") as f:
    for i in range(R_test.shape[0]):
        string = ""
        for j in range(R_test.shape[1]):
            string += str(R_test[i][j])+"\t"
        f.write(string+str(V_test[i])+"\t"+str(1.000)+"\n")

### check preds and RMSE (PES)

In [68]:
# load data:
data = np.loadtxt("data/h4/h4_QZ_data.txt") # .npy for H3, .txt for anything else
X = np.load("data/h4/h4_QZ_coord.npy")
cv_idx = np.load("data/h4/indices_QZ/crossval_indices_1.npy",allow_pickle=True)
train = data[cv_idx[0]]; test = data[cv_idx[1]]
X_test = X[cv_idx[1]]
R_test = test[:, :-1]
V_test = test[:, -1]


# fixed parameters:
num_basis = 59; max_deg = 5; num_atom = 4; e = 3; g = 6;

# indexer matrix:
indexer = atom_indexer(num_atom)

C0 = np.loadtxt("params/h4/c_params_070422_full_fold1_h4_QZ_8e-3_3e-1.out") # optimized parameter
start = time.time()
V_pred = f_pot_bond_wrapper_trpp(C0, num_basis, R_test, X_test, indexer, num_atom, max_deg, e, g)
print(time.time()-start, "s")
# RMSE:
rmse = RMSE(V_pred, V_test)
print('rmse', rmse)
for i, pred in enumerate(V_pred):
    print(V_pred[i], V_test[i])

0.002501964569091797 s
rmse 1.7063738457541575
-3.677772231631733 -2.2950488732
-3.736255992450252 -2.2956569843
-3.7332477731242895 -2.2958077913
-3.782629212872788 -2.2959068964
-3.821560589835787 -2.3200165063
-3.788033634682879 -2.3041433642
-3.669046473365214 -2.3060384857
-3.784522633473792 -2.3074966066
-3.7842259835277403 -2.3074519332
-3.8230448563690356 -2.3074330956
-3.8251148806681927 -2.3076278647
-3.7565360807964443 -2.3422719905
-3.842149310458894 -2.3435281001
-3.7339868042116935 -2.3434812509
-3.856323247511303 -2.3438157793
-3.8574982911180253 -2.3439242543
-3.6953977195302907 -2.3296095361
-3.809018613859112 -2.3314334087
-4.21076440133847 -2.3139475206
-3.8499797276161125 -2.3184492888
-3.845760430933966 -2.2970418156
-3.8315723021697483 -2.3211810082
-3.8799390218494887 -2.3213480983
-3.8678618610343056 -2.3453851809
-4.194524328152556 -2.3174815599
-3.8293038418620027 -2.2976564201
-3.8913719543555616 -2.2977859255
-3.7337074431252866 -2.3212303273
-3.888450304924